# Generated by Django 5.1.1 on 2024-09-13 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosTxts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotranscription',
            name='audio_id',
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
