# Generated by Django 5.1.1 on 2024-09-13 01:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosTxts', '0002_alter_videotranscription_audio_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videotranscription',
            name='audio_id',
        ),
        migrations.CreateModel(
            name='TxtFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videosTxts.videotranscription')),
            ],
        ),
    ]
