# Generated by Django 5.1.1 on 2024-09-13 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videosTxts', '0003_remove_videotranscription_audio_id_txtfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='txtfile',
            name='name',
        ),
    ]
