# Generated by Django 5.1.1 on 2024-09-13 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosTxts', '0004_remove_txtfile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txtfile',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='txt_file', to='videosTxts.videotranscription'),
        ),
    ]
