# Generated by Django 5.1.1 on 2024-09-13 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosTxts', '0005_alter_txtfile_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='txtfile',
            name='video',
        ),
        migrations.AddField(
            model_name='videotranscription',
            name='txt_file',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='video_transcription', to='videosTxts.txtfile'),
            preserve_default=False,
        ),
    ]
